const channels = [
  {
    id: "rai1",
    name: "Rai 1",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Rai_1_-_Logo_2016.svg/200px-Rai_1_-_Logo_2016.svg.png",
    genre: "Generalista",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=632",
  },
  {
    id: "rai2",
    name: "Rai 2",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Rai_2_-_Logo_2017.svg/200px-Rai_2_-_Logo_2017.svg.png",
    genre: "Generalista",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=633",
  },
  {
    id: "rai3",
    name: "Rai 3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Rai_3_-_Logo_2017.svg/200px-Rai_3_-_Logo_2017.svg.png",
    genre: "Generalista",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=634",
  },
  {
    id: "rainews24",
    name: "Rai News 24",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rai_News_24_logo.svg/200px-Rai_News_24_logo.svg.png",
    genre: "News",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1904",
  },
  {
    id: "raisport",
    name: "Rai Sport",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Rai_Sport_logo.svg/200px-Rai_Sport_logo.svg.png",
    genre: "Sport",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=640",
  },
  {
    id: "rai4",
    name: "Rai 4",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rai_4_logo.svg/200px-Rai_4_logo.svg.png",
    genre: "Intrattenimento",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=635",
  },
  {
    id: "rai5",
    name: "Rai 5",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Rai_5_logo.svg/200px-Rai_5_logo.svg.png",
    genre: "Cultura",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=636",
  },
  {
    id: "raipremium",
    name: "Rai Premium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Rai_Premium_logo.svg/200px-Rai_Premium_logo.svg.png",
    genre: "Intrattenimento",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=637",
  },
  {
    id: "raigulp",
    name: "Rai Gulp",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Rai_Gulp_logo.svg/200px-Rai_Gulp_logo.svg.png",
    genre: "Bambini",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=638",
  },
  {
    id: "raiyoyo",
    name: "Rai Yoyo",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rai_Yoyo_logo.svg/200px-Rai_Yoyo_logo.svg.png",
    genre: "Bambini",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=639",
  },
  {
    id: "skysportf1",
    name: "Sky Sport F1",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Sky_Sport_F1_logo.png/200px-Sky_Sport_F1_logo.png",
    genre: "Sport",
    stream: "https://www.vavoo.to/play/4246774056/index.m3u8",
  },
];

module.exports = channels;const channels = [
  {
    id: "rai1",
    name: "Rai 1",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Rai_1_-_Logo_2016.svg/200px-Rai_1_-_Logo_2016.svg.png",
    genre: "Generalista",
    // Stream ufficiale Rai (HLS pubblico)
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=632",
  },
  {
    id: "rai2",
    name: "Rai 2",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Rai_2_-_Logo_2017.svg/200px-Rai_2_-_Logo_2017.svg.png",
    genre: "Generalista",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=633",
  },
  {
    id: "rai3",
    name: "Rai 3",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Rai_3_-_Logo_2017.svg/200px-Rai_3_-_Logo_2017.svg.png",
    genre: "Generalista",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=634",
  },
  {
    id: "rainews24",
    name: "Rai News 24",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Rai_News_24_logo.svg/200px-Rai_News_24_logo.svg.png",
    genre: "News",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=1904",
  },
  {
    id: "raisport",
    name: "Rai Sport",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Rai_Sport_logo.svg/200px-Rai_Sport_logo.svg.png",
    genre: "Sport",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=640",
  },
  {
    id: "rai4",
    name: "Rai 4",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rai_4_logo.svg/200px-Rai_4_logo.svg.png",
    genre: "Intrattenimento",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=635",
  },
  {
    id: "rai5",
    name: "Rai 5",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Rai_5_logo.svg/200px-Rai_5_logo.svg.png",
    genre: "Cultura",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=636",
  },
  {
    id: "raipremium",
    name: "Rai Premium",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Rai_Premium_logo.svg/200px-Rai_Premium_logo.svg.png",
    genre: "Intrattenimento",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=637",
  },
  {
    id: "raigulp",
    name: "Rai Gulp",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Rai_Gulp_logo.svg/200px-Rai_Gulp_logo.svg.png",
    genre: "Bambini",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=638",
  },
  {
    id: "raiyoyo",
    name: "Rai Yoyo",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Rai_Yoyo_logo.svg/200px-Rai_Yoyo_logo.svg.png",
    genre: "Bambini",
    stream: "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=639",
  },
];

module.exports = channels;
